version: 2
jobs:

  inspect-server:
    docker:
      - image: "circleci/node:12.16.3"

    working_directory: ~/repo

    steps:
      # Check Out Git Code
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Install Dependencies
      - run:
          name: Install Project Dependencies
          command: yarn install

      # Save the dependency cache
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      # Make Report Directory
      - run: mkdir reports

      # Run Jest
      - run:
          name: Run Jest Suite on Client
          command: |
            cd client
            ./node_modules/.bin/jest

      # Run EsLint
      - run:
          name: Run ESLint On Server
          command: |
            cd server
            ./node_modules/.bin/eslint ./ --format junit --output-file ../reports/eslint/eslint-server.xml
          when: always

      # Run EsLint
      - run:
          name: Run ESLint On Client
          command: |
            cd client
            ./node_modules/.bin/eslint ./ --format junit --output-file ../reports/eslint/eslint-client.xml
          when: always

      # Upload results
      - store_test_results:
          path: reports

      - store_artifacts:
          path: ./reports/eslint/eslint-server.xml

      - store_artifacts:
          path: ./reports/eslint/eslint-client.xml

      - store_artifacts: # upload test coverage as artifact
          path: ./client/coverage/lcov.info
          prefix: tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - inspect-server
